create table roles
(
    id          int8 generated by default as identity,
    description varchar,
    name        varchar,
    primary key (id)
);

create table users
(
    id       int8 generated by default as identity,
    username varchar,
    email    varchar,
    password varchar,
    blocked  boolean,
    role_id  int8 not null,

    foreign key (role_id) references roles,

    primary key (id)
);

INSERT INTO roles (id, name, description) VALUES (default, 'CLIENT', null);
INSERT INTO roles  (id, name, description) VALUES (default, 'ADMIN', null);