create table roles
(
    id          int8 generated by default as identity,
    description varchar,
    name        varchar,

    primary key (id)
);

create table users
(
    id       int8 generated by default as identity,
    username varchar,
    email    varchar,
    first_name     varchar,
    second_name  varchar,
    password varchar,
    blocked  boolean,
    role_id  int8 not null,

    primary key (id),
    foreign key (role_id) references roles
);

create table meets
(
    id          int8 generated by default as identity,
    name        varchar,
    date        date,
    start_time  time,
    end_time    time,
    link        varchar,
    description varchar,
    creator_id  int8,

    primary key (id),
    foreign key (creator_id) references users
);

create table guest_status
(
    id     int8 generated by default as identity,
    status varchar,

    primary key (id)
);

create table meet_guests
(
    id        int8 generated by default as identity,
    meet_id   int8,
    guest_id  int8,
    status_id int8,

    primary key (id),
    foreign key (guest_id) references users,
    foreign key (meet_id) references meets,
    foreign key (status_id) references guest_status
)